require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - '**/config.ru'
    - '**/Rakefile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'app/controllers/admin/base_controller.rb'
    - 'app/interactors/data_importer/implementations/leopard_solutions/requisitions_from_notification/target_processor.rb'
    - 'spec/interactors/data_importer/implementations/leopard_solutions/requisitions/base_spec.rb'
Capybara/FeatureMethods:
  Enabled: false
Documentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
Metrics/MethodLength:
  Max: 15
Metrics/AbcSize:
  Max: 20
Metrics/LineLength:
  Max: 100
Rails:
  Enabled: true
Rails/HttpStatus:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': ()
    '%w': ()
Style/RaiseArgs:
  EnforcedStyle: compact
Style/RegexpLiteral:
  StyleGuide: slashes
Style/SymbolArray:
  EnforcedStyle: brackets
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'spec/**/*'
